### ISSUE TITLE
Authentication Failed

### ISSUE THREAD

**Issue by prov3it** [PrimalZed/kobo-book-downloader-vue#1]
I follow your instructions to the letter and have used subdavis's script succesfully, but i cannot login. Im using an e-mail address. It says Authentication failed. Im using the exe file on Windows.

**Comment by PrimalZed** [comment]
Thank you for letting me know.

It looks like the text I was looking for to get the signin information changed in the short time since I made this. I hope they aren't going to be doing that frequently!

You can see the change I made here: 680d4a7d814407b4a6438e89bdc09eb7ee42a3f3

I uploaded new version of the .exe here: https://github.com/PrimalZed/kobo-book-downloader-vue/releases/tag/v1.0.1

Please let me know whether that works

**Comment by prov3it** [comment]
It works! Thank you very much. Where can i buy you a coffee?

**Comment by PrimalZed** [comment]
I appreciate it, but I don't (currently?) have any place for donations. Glad it worked for you!

**Comment by Tenshi-lab** [comment]
Sorry, but Authentication failed once again.

**Comment by PrimalZed** [comment]
> Sorry, but Authentication failed once again.

I was unable to reproduce issues with authentication using the latest release. Can you open a new ticket?

To help with diagnosing the issue, before you click the Sign In button (but after entering username/email, password, and pasting the Captcha), can you do the following:

1. Open browser dev tools (press F12 on the keyboard)
2. Click Sign In button on the web page
3. In browser dev tools, find the Network tab
4. If there are any failed requests in the Network tab, please let me know which request(s) failed
5. In the Network tab, find and click on the `signin?returnUrl=...` request (it should be near the top of the request list)
6. In the Response tab of the request panel, see if you can find a "partner-sign-in" and "primary-action" section, similar to the one in the screenshot below

![image](https://github.com/PrimalZed/kobo-book-downloader-vue/assets/4495480/64d96781-d995-4a8d-b27d-ba287fd96b64)

Does there appear to be any differences between what you find in the signin request's response and my screenshot above, particularly in the `class` value of the kobo sign-in link?

(again, please create a new Issue rather than replying here.)
